### ISSUE TITLE
"failed to fill whole buffer" errors

### ISSUE THREAD

**Issue by mitya52** [google-research/deduplicate-text-datasets#14]
Hi,

I have tried to run the code on simple string and count-occurrences fails with "failed to fill whole buffer" error.

Here are steps to reproduce:

1. run ```./target/debug/dedup_dataset make --data-file dup.txt```, data file dup.txt contains simple string "aaabbb"
2. then run ```./target/debug/dedup_dataset count-occurrences --data-file dup.txt --query-file query.txt```, where query.txt contains
- "bb"
  expectation: ```Number of times present: 2```
  reality: ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/main.rs:275:31```;
- "ab"
  expectation: ```Number of times present: 1```
  reality: ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/main.rs:297:31```;
- "b"
  expectation: ```Number of times present: 2```
  reality: ```Number of times present: 1```;

May be I'm doing something wrong? Thanks.

**Comment by carlini** [comment]
Ah sorry this is a bug with something from the rewrite. I've updated to the new version of the code if you pull -- please let me know if it works correctly.

**Comment by mitya52** [comment]
Thanks, all "failed to fill whole buffer" errors gone with fix!
