### ISSUE TITLE
Should newline char be removed

### ISSUE THREAD

**Issue by cperiz** [google-research/deduplicate-text-datasets#16]
Hi, So I notice that this read [here](https://github.com/google-research/deduplicate-text-datasets/blob/master/scripts/count_occurrences.py#L53) adds a `\n` char to the end of the query. This then causes an issue with the count if its not actually an end-of-line. Should there be a `.strip()` added here? 

`arr = open(args.query_file,"rb").read().strip()`

Thanks.

**Comment by carlini** [comment]
This python command doesn't itself add a newline to the file. It only reads what's already in the file. If you don't want a newline then you should remove it from the input file. For example, if you're writing to it with echo, this by default adds a newline to the end.
