### ISSUE TITLE
Fix to issue #17 limits cmd_merge to be single-threaded

### ISSUE THREAD

**Issue by kleinj** [google-research/deduplicate-text-datasets#19]
Hi,

it looks like the fix for issue #17, which puts some limits on the number of threads in cmd_merge, is a bit too aggressive, resulting in only using a single thread even for big workloads:

https://github.com/google-research/deduplicate-text-datasets/blob/ad86c7f65ac626581fe3a4277106309bc6b50c23/src/main.rs#L1020-L1023

`texts.len()` is equal to `nn` (the number of input parts), I think you want something like

```
    let num_threads = std::cmp::min(num_threads, std::cmp::max((texts_len.iter().sum::<usize>() as i64 - 1024)/10, 1));
```
instead.

**Comment by carlini** [comment]
Oops. Yeah that's bad. Let me fix this.

**Comment by TristanThrush** [comment]
I just added the great suggestion by @kleinj as a PR: https://github.com/google-research/deduplicate-text-datasets/pull/22/files.

I was running the code on a 10's of gigabyte dataset and this fix makes the code only run in about 2 hours with a lot of CPUs (it would've taken 100's of hours without this fix). Let me know what you think @carlini!

**Comment by carlini** [comment]
This should have been fixed.
