### ISSUE TITLE
how to deduplicate huggingface datasets 

### ISSUE THREAD

**Issue by StephennFernandes** [google-research/deduplicate-text-datasets#21]
Hey there, excellent work on this repo and the paper. 

I wanted to know on how could i use this to deduplicate my huggingface custom dataset. that i have custom developed and cleaned. 

that has been saved as `custom_dataset.save_to_disk("dataset_path")`

and can be loaded as `custom_dataset = datasets.load_from_disk("dataset_path")`

**Comment by carlini** [comment]
A while ago someone sent a PR to do this

https://github.com/google-research/deduplicate-text-datasets/pull/6

But I haven't tested it on the latest code -- maybe you could try that and see if it would work for you?

**Comment by TristanThrush** [comment]
I just had the same question as you @StephennFernandes, and I found this repo which can be installed with pip: https://github.com/ChenghaoMou/text-dedup. It looks like text-dedup has a more plug-and-play version of this repo? I followed the documentation [here](https://chenghaomou.github.io/text-dedup/modules.html#suffix-array-substring-exact-deduplication-examples) and used it on a huggingface dataset with `embedder.embed_bash(my_hf_dataset["text"])`

**Comment by cakiki** [comment]
@TristanThrush This only works on datasets that fit in memory though, right? I think `my_hf_dataset["text"]` loads the entire column into a list. I'm also trying to solve this using a larger-than-memory dataset, have you had any luck with this?

**Comment by TristanThrush** [comment]
@cakiki possibly. I have a machine with 100's of GB of memory, so it hasn't been a problem for me. I think that both this repo and the alternative repo require a lot of memory?

**Comment by cakiki** [comment]
@TristanThrush I don't think this repo requires you to load everything into memory though. I'll try running Teven's PR and report back.

**Comment by TristanThrush** [comment]
@cakiki we might be able to resolve this issue on the text-dedup side: https://github.com/ChenghaoMou/text-dedup/issues/5

**Comment by carlini** [comment]
This repository does require that the dataset itself fit in memory. Closing because I've now merged #6.
