### ISSUE TITLE
Inplementation of NearDup(approximate match)

### ISSUE THREAD

**Issue by Yaoming95** [google-research/deduplicate-text-datasets#27]
In the paper, you used two methods: suffix array for exact matches and Minhash for approximate matches. 
Currently, the repo only contains a suffix array-based one. Kindly ask if you will release the implementation of the Minhash-based one for NearDup method in your paper.

**Comment by daphnei** [comment]
Unfortunately, we cannot release the MinHash code we used as it relies on internal Google infrastructure.

However, there are many good open-source implementations of MinHash which you should be able to take advantage of.
