### ISSUE TITLE
How to restore the result data after deduplication (remove invisible characters)

### ISSUE THREAD

**Issue by greenriver777** [google-research/deduplicate-text-datasets#29]
When i run 'bash scripts/deduplicate_single_file.sh data/squad.validation ./res/squad 4 8', then i got the deduplicated res as follows
![image](https://github.com/google-research/deduplicate-text-datasets/assets/132532882/6282b1ba-07d6-4c21-90ca-e11789622a31)
How to remove characters that produced by function sep() in load_dataset.py

**Comment by carlini** [comment]
You should just be able to split on "\xff\xff" (and remove the next 4 bytes depending on how you've built the dataset), which are the special characters that's been introduced, as long as that's not anywhere else in your file. Let me know if you have problems and I can re-open this.
