### ISSUE TITLE
How to dedup between two datasets?

### ISSUE THREAD

**Issue by mralexis1** [google-research/deduplicate-text-datasets#3]
A practical situation is that given two datasets A and B, we want to remove the data in A that has huge overlap with B. Is there a command that I could use to achieve this functionality? There is only command of single-document or single-document pairs in the [readme on finding duplicates](https://github.com/google-research/deduplicate-text-datasets#finding-duplicates).

**Comment by carlini** [comment]
Ah yes, we actually have this feature and should document it.

If you create a suffix array for `file_1` and `file_2` (to get the suffix arrays `file_1.table.bin` and `file_2.table.`bin) then you can run

```bash
cargo run similar_parallel file_1 file_2
```

And this will find for you all substrings that are contained in `file_1` that match substrings in `file_2` and vice versa. The implementation of this is here

https://github.com/google-research/deduplicate-text-datasets/blob/1c89d70f5461199c98f84132b15bf0b6fc4645ca/src/main.rs#L846-L964

The output format is a bit (a lot... ugly): it will dump files to `/tmp` named `dups_${file_1}_${file_2}` where each line has the example and offset that should be removed. I have a new version of this code that outputs to a binary format to save space, and will push that (breaking) change at some point.

**Comment by mralexis1** [comment]
Thanks for the very quick reply, @carlini ! Some follow-up questions:

1. The paper mentioned two methods: Exact Substring Duplication and Approximate Matching with MinHash, does the `similar_parallel` functionality contain both? 
2. The paper mentioned `we select k = 50 tokens as the minimum matching substring length`. If my understanding is correct, that means I should look into `dups_${file_1}_${file_2}` and check whether offset > 50?
3. To dedup between two datasets, I would need to run the `similar_parallel` command for `len(d1) * len(d2)` times. Is this correct?

**Comment by carlini** [comment]
1. This open source code only reproduces exact substring deduplication. The approx deduplication implementation is used for large-scale production tasks at Google and so can not be made open source.
2. The code will automatically handle this for you, and only report matches of length 50.
3. Nope. You just need to run once, and it will give you all matches between the two datasets. Suffix trees are magic!

**Comment by mralexis1** [comment]
Sounds good. So instead of 

```
cargo run similar_parallel file_1 file_2
```

We should use 

```
cargo run similar_parallel dataset_1_dir dataset_2_dir
```
?

**Comment by carlini** [comment]
No, you'll want to merge all of the files in each dataset together to one meta-dataset, and then intersect the two meta datasets. (Otherwise you'll need to do n^2 comparisons between files.)

**Comment by mralexis1** [comment]
Hmm not sure I understand this correctly. So say that the first dataset has m files or documents, and the second has n. Then what I should do is to create a single file `merged_d1` that concatenates the m files, and `merged_d2` that concatenates the n files. Then I run build suffix array, and run the `similar_parallel` command? If so, should we also maintain offset maps to convert the duplicated offsets back to its corresponding file and its index in the file?

**Comment by carlini** [comment]
Yeah -- this is the idea. You can see how we do such a merging in this file

https://github.com/google-research/deduplicate-text-datasets/blob/master/scripts/load_dataset.py

Which creates a parallel file_1.size which tracks how long each example is. This is what lets the code print out (example, offset) matches.
