### ISSUE TITLE
what is the input dataset format for custom dataset?

### ISSUE THREAD

**Issue by mittsommer** [google-research/deduplicate-text-datasets#31]
Hello guys, i am trying to dedup my custom dataset, but there seems no templete for dataset format in the repo.
So i want to confirm that, thank you guys

**Comment by carlini** [comment]
You should be able to load any random text file in and it will work. If you work through an example in 

https://github.com/google-research/deduplicate-text-datasets/blob/master/scripts/load_dataset_hf.py

you should see how to do it. Let me know if you have any questions.
