### ISSUE TITLE
Retain one instance per duplicate

### ISSUE THREAD

**Issue by RobinQrtz** [google-research/deduplicate-text-datasets#32]
Hi!

Thank for this incredibly fast code!

I noticed that when deduplicating all duplicate instances are being removed, instead of keeping at least one.

The byte-spans that we use in the end to remove the duplicates, potentially consist of combinations of smaller duplicates.

Is there any smart and efficient way to use this information to keep at least one instance for each duplicate?

Thanks!

**Comment by suniy83** [comment]
Thank you for providing the solution.
I did the same change in `cmd_self_similar`, but the code still removes both duplicates or keep both (based on the Len threshold). Are there other modifications in other functions or scripts that need to be done in order to `retain one instance per duplicate`?
