### ISSUE TITLE
Why not use Simhash?

### ISSUE THREAD

**Issue by Ethan-yt** [google-research/deduplicate-text-datasets#4]
Since Google has shown that Simhash is practically useful for identifying near-duplicates in web documents belonging to a multi-billion page repository ([Detecting Near-Duplicates for Web Crawling](http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/33026.pdf)). In your paper, you choose minhash for approximate matching. Why not use Simhash in this scenario?

**Comment by daphnei** [comment]
Hi Ethan,
Thanks for your question.

The point of our paper was not to do the best possible deduplication, and it's likely our deduplication methods could be improved upon. Rather, the goal of our paper was to show that doing more thorough deduplication than is currently standard in the field is a good thing, as it reduces train/test overlap and reduces memorization. 

Empirically, the minhash algorithm we employed was very effective at identifying near-duplicates (see some of the qualitative examples in the appendix), so we didn't try to improve further by looking for other methods.

**Comment by AWNystrom** [comment]
There's also been work since that's shown minhash to often be the better choice: ["In Defense of MinHash Over SimHash"](http://proceedings.mlr.press/v33/shrivastava14.pdf)

**Comment by Ethan-yt** [comment]
This work is very impressing. Thanks for the answer. @daphnei @AWNystrom
