### ISSUE TITLE
[Bug] Out of range error when counting occurrences on a custom suffix array

### ISSUE THREAD

**Issue by WWWonderer** [google-research/deduplicate-text-datasets#45]
Hello!

In some rare occasions, this bug can be triggered when counting occurrences of a pattern:
```
thread 'main' panicked at src\main.rs:284:40:
range end index 133018772 out of range for slice of length 133018768
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Below is a demo code to trigger this bug. To run the code, you first need to have a custom tokenized squad dataset as your suffix array. I constructed mine by concatenating context and question pairs of squad, with `tiktoken.gpt2`'s `eot_token` as separator (instead of the `sep()` function's `b"\xff\xff" + struct.pack("<I", UID)`). The concatenated dataset as well as the suffix array can be found here: .https://drive.google.com/drive/folders/1-c3wc4WClZJhed3hVgadYQvlA5CEyAwE?usp=sharing. Assuming you put the files in `data/squad`, run the following python code:
```
import numpy as np
import tiktoken
import subprocess
import platform
import struct

tokenizer = tiktoken.get_encoding('gpt2')
window_size = 10

# tokenized to: ' indis', 'put', 'ably'
# tokens are: [49919, 1996, 1346]
# byte representation in hex: 06 00 00 00 FF C2 CC 07 42 05
problematic_str = " indisputably"
problematic_str_tokens = tokenizer.encode_ordinary(problematic_str)
problematic_str_bytes = np.array(problematic_str_tokens, dtype=np.uint16).view(np.uint8).tobytes()
problematic_str_bytes_with_len = struct.pack("<L", len(problematic_str_bytes)) + problematic_str_bytes

# for simplicity of demo, just delete these manually after running script
open('problematic_str_bytes', 'wb').write(problematic_str_bytes)
open('problematic_str_bytes_with_len', 'wb').write(problematic_str_bytes_with_len)

# launch count-occurrences(-multi) rust scripts
path_separator = "\\" if platform.system() == "Windows" else "/"
command = [
    f".{path_separator}target{path_separator}debug{path_separator}dedup_dataset",
    "count-occurrences",
    "--data-file", f"data{path_separator}squad{path_separator}train",
    "--query-file", "problematic_str_bytes",
    "--load-disk"
]
command2 = [
    f".{path_separator}target{path_separator}debug{path_separator}dedup_dataset",
    "count-occurrences-multi",
    "--data-file", f"data{path_separator}squad{path_separator}train",
    "--query-file", "problematic_str_bytes_with_len",
    "--load-disk"
]
result_count_occurrences = subprocess.run(command, capture_output=True, text=True, shell=(platform.system() == "Windows"))
result_count_occurrences_multi = subprocess.run(command2, capture_output=True, text=True, shell=(platform.system() == "Windows"))
print(result_count_occurrences.stdout)
if result_count_occurrences.stderr: print(result_count_occurrences.stderr)
print(result_count_occurrences_multi.stdout)
if result_count_occurrences_multi.stderr: print(result_count_occurrences_multi.stderr)
```
you should get this bug:
```
thread 'main' panicked at src\main.rs:284:40:
range end index 133018772 out of range for slice of length 133018768      
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at src\main.rs:278:40:
range end index 133018772 out of range for slice of length 133018768      
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have traced the bug to be caused by the following reason: during the binary search of `count_occurances` and `count_occurances_memory`, it is possible (although very rare) that we can reach the end of the suffix array without finding the pattern. If that is the case, we would have `low` equal to `size/(size_width as u64)`, and it will trigger an out of range error in the next line ` let pos: usize = table_load_filebuffer(&table, low as usize, size_width);`, as it tries to read the next `size_width` bits from the end of the suffix array. 

In this example, the token `indisputably` is tokenized (using `tiktoken gpt2`) into `[49919, 1996, 1346]`, where `49919` is `FF C2` in hex. This `FF` triggers the search to reach the end of the suffix array.  I also tried to reproduce the bug with the provided `load_dataset_hf.py` script, which uses `sep()` function instead of `eot_token` as separator and the script works fine. (is `b"\xff\xff"` from `sep()` an intentional design to specifically prevent this kind of scenario?) I also tried using `openwebtext` as the suffix array with `eot_token` as separator, and the script also works fine. Out of a lot of queries, only ` indisputable` triggered it on squad suffix with `eot_token` as separator. So it is very rare, but very annoying to debug once it happens... 

I have made a pull request to fix this bug, can it be merged it if it is good enough? It would mean a lot to me :) Thanks!

**Comment by carlini** [comment]
Wow, thanks for the detailed description of the bug here! I'll go take a look at the PR.
